account/urls.py
from django.urls import path 
from .views import registration_view



app_name = 'account' 

urlpatterns = [
    path('register/', registration_view, name='registration_view'),
    #path('password/', change_password, name='change_password'),
] 
    

blog/urls.py
from django.urls import path 
from .views import post_detail, PostListView


app_name = 'blog' 

urlpatterns = [
     # post views 
     path('', PostListView.as_view(), name='post_list'), 
     path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'), 
    ]

ecommerce/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, about_page, contact_page, dashboard
from ecommerce.views import login_form, order_details, tee
from rest_framework.routers import DefaultRouter
from products.api.urls import router_products
from orders.api.urls import router_orders

class ContainerRouter(DefaultRouter):
    def register_router(self, router):
        self.registry.extend(router.registry)

router = ContainerRouter()
router.register_router(router_products)
router.register_router(router_orders)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_page),
    path("about/", about_page, name='about_page'),
    path("contact/", contact_page, name='contact_page'),
    path("tee/", tee, name='tee'),
    #path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('login/', login_form, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path("register/", register_page, name="register"),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/order/<int:order_id>/', order_details, name='order_details'),
    #path('dashboard/allow_change_password/', change_password, name='allow_change_password'),
    # reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('api/', include(router.urls)),
    # path('api/products/', include('products.api.urls', namespace='products_api')),
    # path('api/orders/', include('orders.api.urls', namespace='orders_api')),

    path("api-auth/", include("rest_framework.urls")),
    path("api/rest-auth/", include("rest_auth.urls")),
    path("api/rest-auth/registration/", include("rest_auth.registration.urls")),
    


    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('products/', include('products.urls', namespace='products')),
    
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('delivery/', include('Delivery.urls', namespace='delivery')),
    path('ship_station/', include('ship_station.urls', namespace='ship_station')),
    path('__debug__/', include(debug_toolbar.urls)),
    
    
    
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "SAM&M Trade Admin"
admin.site.site_title = "SAM&M Trade Admin Portal"
admin.site.index_title = "Contol Panel"

account/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import Group, Permission, PermissionsMixin
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
#from django.contrib.auth import get_user_model
#User = get_user_model()

# Create your models here.
class CustomersManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Customers must have an email")
        #if not username:
            #raise ValueError("Customers must have an username")
        user = self.model(
                email=self.normalize_email(email),
                #username=username,
                
                )

        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            #username=username,
        
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.ein_verified = False
        user.save(using=self._db)
        return user



class Customers(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="email", max_length=70, unique=True)
    username = models.CharField(max_length=30)
    company_name=models.CharField("Business Legal Name", max_length=30)
    first_name = models.CharField("Company Owner's First Name", max_length=30)
    last_name = models.CharField("Company Owner's Last Name", max_length=30)
    stripe_customer = models.CharField(max_length=150) 
    ein = models.CharField(verbose_name="Tax Payer Number", max_length=15, blank=True, null=True, unique=True)
    ein_verified = models.BooleanField(verbose_name="TPN Verified?", default=False)
    phone = PhoneNumberField(null=False, blank=False)
    admin = models.BooleanField(default=False) # a superuser
    staff = models.BooleanField(default=False) # a admin user; non super-user
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomersManager()

    

    def __str__(self):
        return self.email

    
    class Meta:
        verbose_name = "customer"
        verbose_name_plural = "customers"
        ordering = ("date_joined",)

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
    
    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def get_legal_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.company_name

    def email_customer(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        
        '''
        from django.core.mail import send_mail
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    

account/forms.py
from django import forms  

from .models import Customers
#from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
#User = get_user_model()

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text= "Required. Add a valid email address", required=True)
    phone= PhoneNumberField(widget=forms.TextInput(attrs={'placeholder': "e.g. +12107249073"}), required=False)
    class Meta:
        model = Customers
        #fields = UserCreationForm.Meta.fields + ('custom_field',)
        fields = ("email", "company_name", "first_name","last_name","phone","ein", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = Customers.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is taken")
        return email


    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password2 != password:
            raise forms.ValidationError("Passwords must match!")
        return data

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        qs = Customers.objects.filter(phone=phone)
        if qs.exists():
            raise forms.ValidationError("Phone number already in use")
        if len(phone) == 10 and phone[0:2] != "+1":
            phone = "+12107249045"

        return phone    

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, get_user_model
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .forms import RegistrationForm
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from products.models import Category, Product
from account.models import Customers
import stripe
from django.core.mail import send_mail
from account.tasks import info_admins





def registration_view(request):
    context = {}

    if request.user.is_anonymous == False:
        return redirect('dashboard')

    elif request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            
            form.save()
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")

            customer = Customers.objects.get(email=email)
            created_customer = stripe.Customer.create(
                description=email,
                email=email
            )
            customer.stripe_customer = created_customer.id
            customer.save()
            
            account = authenticate(email=email, password=raw_password)
            login(request, account)

            info_admins(email)


            return redirect('dashboard')
        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
        context['registration_form'] = form

    return render(request, 'register2.html', context)

account/templates/register2.html
{% extends 'base.html' %}
{% block content %}


      
<h1>Register</h1>
  <div class="login-form">
    <form action="{% url 'account:registration_view' %}" method="post">
      {% csrf_token %}
      {% for field in registration_form %}
      
        <p>
            {{ field.label_tag}}
            {{ field }}
          </p>
            <!--{% if field.help_text %}
                <small style='color:grey;'> {{ field.help_text }}</small>
            {% endif %}-->
          <p>
            {% for error in field.errors %}
                <p style='color:red;'>{{ error }}</p>
            {% endfor %}
          </p>
      {% endfor %}
      <p><input type="submit" value="Register"></p>
    </form>
    

  </div>
  
{% endblock %}

{% block blank %}
    
<div class="breadcrumb-area pt-15 pb-15">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!--=======  breadcrumb container  =======-->
        
        <div class="breadcrumb-container">
          <nav>
            <ul>
              <li class="parent-page"><a href="/">Home</a></li>
              <li><a href="{% url 'account:registration_view' %}">Register</a></li>
            </ul>
          </nav>
        </div>
        
        <!--=======  End of breadcrumb container  =======-->
      </div>
    </div>
  </div>
</div>

  <!--=====  End of breadcrumb area  ======-->
  
  <!--=============================================
  =            Register page content         =
  =============================================-->

  <div class="page-section mb-50">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
        
        <form action="{% url 'account:registration_view' %}" method="post">
          {% csrf_token %}
          {% for field in registration_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        
        
    </div>
{% endfor %}
          <div class="login-form">

            <h4 class="login-title">Register</h4>
            
            <div class="row">
              <div class="col-md-6 col-12 mb-20">
                <label for="id_first_name">Company Owner's First Name:</label>
                <input class="mb-0" placeholder="Company Owner's First Name" type="text" name="first_name" maxlength="30" required="" id="id_first_name">
                
              </div>
              <div class="col-md-6 col-12 mb-20">
                <label for="id_last_name">Company Owner's Last Name:</label>
                <input placeholder="Company Owner's Last Name" type="text" class="mb-0" name="last_name" maxlength="30" required="" id="id_last_name">
              
              </div>
              <div class="col-md-12 mb-20">
                <label for="id_company_name">Business Legal Name:</label>
                <input class="mb-0" placeholder="Business Legal Name" type="text" name="company_name" maxlength="30" required="" id="id_company_name">
                
              </div>
              <div class="col-md-12 mb-20">
                <label for="id_email">Email Address*</label>
                <input placeholder="Email Address" class="mb-0" type="email" name="email" maxlength="60" autofocus="" required="" id="id_email">
              </div>
              <div class="col-md-12 mb-20">
                <label for="id_phone">Phone:</label>
                <input class="mb-0" type="tel" name="phone" placeholder="2107249073" id="id_phone">
              </div>
              <div class="col-md-12 mb-20">
                <label for="id_ein">Tax Payer Number:</label>
                <input class="mb-0" type="text" name="ein" maxlength="15" id="id_ein">
              </div>
              <div class="col-md-6 mb-20">
                <label for="id_password1">Password:</label>
                <input class="mb-0" type="password" placeholder="Password" name="password1" autocomplete="new-password" required="" id="id_password1" aria-autocomplete="list">
                
              </div>
              <div class="col-md-6 mb-20">
                <label for="id_password2">Confirm Password:</label>
                <input class="mb-0" type="password" placeholder="Confirm Password" name="password2" autocomplete="new-password" required="" id="id_password2">
              </div>
              <div class="col-12">
                <button class="register-button mt-0">Register</button>
              </div>
              
            </div>
            
          </div>

        </form>
      </div>
      
    </div>
  </div>
</div>

<!--=====  End of Login Register page content  ======-->
  
    <!--=====  End of Login Register page content  ======-->
{% endblock %}