blog/urls.py
from django.urls import path 
from .views import post_detail, PostListView


app_name = 'blog' 

urlpatterns = [
     # post views 
     path('', PostListView.as_view(), name='post_list'), 
     path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'), 
    ]

ecommerce/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, about_page, contact_page, dashboard
from ecommerce.views import login_form, order_details, tee
from rest_framework.routers import DefaultRouter
from products.api.urls import router_products
from orders.api.urls import router_orders

class ContainerRouter(DefaultRouter):
    def register_router(self, router):
        self.registry.extend(router.registry)

router = ContainerRouter()
router.register_router(router_products)
router.register_router(router_orders)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_page),
    path("about/", about_page, name='about_page'),
    path("contact/", contact_page, name='contact_page'),
    path("tee/", tee, name='tee'),
    #path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('login/', login_form, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path("register/", register_page, name="register"),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/order/<int:order_id>/', order_details, name='order_details'),
    #path('dashboard/allow_change_password/', change_password, name='allow_change_password'),
    # reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('api/', include(router.urls)),
    # path('api/products/', include('products.api.urls', namespace='products_api')),
    # path('api/orders/', include('orders.api.urls', namespace='orders_api')),

    path("api-auth/", include("rest_framework.urls")),
    path("api/rest-auth/", include("rest_auth.urls")),
    path("api/rest-auth/registration/", include("rest_auth.registration.urls")),
    


    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('products/', include('products.urls', namespace='products')),
    
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('delivery/', include('Delivery.urls', namespace='delivery')),
    path('ship_station/', include('ship_station.urls', namespace='ship_station')),
    path('__debug__/', include(debug_toolbar.urls)),
    
    
    
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "SAM&M Trade Admin"
admin.site.site_title = "SAM&M Trade Admin Portal"
admin.site.index_title = "Contol Panel"

ship_station/urls.py
from django.urls import path
from ship_station.views import IndexView, InventoryLogListView, ProductDetailView, ProductListView, decrease, increase, lookup, update_source_file


app_name = 'ship_station'


urlpatterns = [
    path('update_source_file/',update_source_file,name='update_source_file'),
    path('lookup/',lookup,name='lookup'),
    path('index/',IndexView.as_view(),name='index'),
    path('increase/',increase,name='increase'),
    path('decrease/',decrease,name='decrease'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('inventorylogs/', InventoryLogListView.as_view(), name='inventorylog-list'),
]

ship_station/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.db.models import Sum
from decimal import Decimal



    
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

class File(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


# Create your models here.
class SoftDeletableQS(models.QuerySet):
   """A queryset that allows soft-delete on its objects""" 

   def delete(self, **kwargs):
       self.update(deleted_ts=timezone.now(), **kwargs)

   def hard_delete(self, **kwargs):
       super().delete(**kwargs)

class SoftDeletableManager(models.Manager):
   """Manager that filters out soft-deleted objects"""
   def get_queryset(self):
       return SoftDeletableQS(
           model=self.model, using=self._db, hints=self._hints
       ).filter(
           deleted_ts__isnull=True
       )

class SoftDeletableModel(models.Model):
   """An abstract parent class for soft-deletable models"""
   objects = SoftDeletableManager()
   archive_objects = models.Manager() 

   deleted_ts=models.DateTimeField(blank=True,null=True, editable=False)

   class Meta:
       abstract=True
   
   def delete(self):
       """Softly delete the object"""
       self.deleted_ts = timezone.now()
       self.save()

       

   
   def hard_delete(self):
       """Remove the object permanently from the database"""
       super().delete()

class BaseModel(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, null=True, unique=False, editable=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
       abstract = True

class Brand(BaseModel, SoftDeletableModel):
    name=models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return str(self.name)


class ArchivedBrandManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedBrandManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedBrand(Brand):
    """Archive transactions - hard-deletable"""
    objects = ArchivedBrandManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()

class Model(BaseModel, SoftDeletableModel):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    name=models.CharField(max_length=20, blank=False, null=True)
    styleID = models.CharField(max_length=20, blank=False)


    def __str__(self):
        return "{} | {}".format(self.brand, self.name)

class ArchivedModelManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedModelManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedModel(Model):
    """Archive transactions - hard-deletable"""
    objects = ArchivedModelManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()



class Color(BaseModel, SoftDeletableModel):
    name=models.CharField(max_length=100, blank=False, null=True)
    colorCode=models.CharField(max_length=100,blank=False, null=False)


    def __str__(self):
        return str(self.name)

class ArchivedColorManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedColorManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedColor(Color):
    """Archive transactions - hard-deletable"""
    objects = ArchivedColorManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()

class Size(BaseModel, SoftDeletableModel):
    name=models.CharField(max_length=100, blank=False, null=True)
    sizeCode=models.IntegerField(blank=False, null=False)

    def __str__(self):
        return str(self.name)

class ArchivedSizeManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedSizeManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedSize(Size):
    """Archive transactions - hard-deletable"""
    objects = ArchivedSizeManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()


class Product(BaseModel, SoftDeletableModel):
    sku = models.CharField(max_length=100, blank=True, null=True)
    #skuID_Master = models.CharField(max_length=100, blank=True, null=True)
    #ean = models.CharField(max_length=500, blank=False, null=True)
    gtin = models.CharField(max_length=500, blank=False, null=True)
    #name = models.CharField(max_length=60, blank=True, null=True, help_text='title of the product')
    model = models.ForeignKey(Model, on_delete=models.CASCADE, blank=True, null=True, help_text='if model is unfamiliar, search item ean at upcitemdb.com')
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, blank=True, null=True)
    caseQty = models.IntegerField(blank=True, null=True)
    #ean2 = models.TextField(blank=False, null=True)
    note = models.CharField(max_length=120, blank=True, null=True, help_text='type your notes here about this item')

    def __str__(self):
        return "{} | {} | {}".format(str(self.model),str(self.size),str(self.color))

    @property
    def current_stock(self):
        if self.logs.all():
            try:
                total = self.logs.all().aggregate(Sum('quantity'))['quantity__sum']
                return int(total)
            except:
                return 0
        return 0
        

class ArchivedProductManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedProductManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedProduct(Product):
    """Archive transactions - hard-deletable"""
    objects = ArchivedProductManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()

class InventoryLog(BaseModel, SoftDeletableModel):
    product= models.ForeignKey(Product, on_delete=models.CASCADE, blank=False, null=True, related_name='logs')
    quantity = models.IntegerField(default=0, blank=False, null=True)

    def __str__(self):
        return str(self.product)

    @property
    def current_stock(self):
        total = InventoryLog.objects.filter(product=self.product).aggregate(Sum('quantity'))['quantity__sum']
        return total


class ArchivedInventoryLogManager(models.Manager):
    def get_queryset(self):
        return super(ArchivedInventoryLogManager, self).get_queryset().filter(deleted_ts__isnull=False)

class ArchivedInventoryLog(InventoryLog):
    """Archive transactions - hard-deletable"""
    objects = ArchivedInventoryLogManager()
    #objects = models.Manager()

    class Meta:
        proxy=True

    def delete(self):
        """Permanently delete the entry"""
        super().hard_delete()

ship_station/forms.py
from django import forms
from .models import File

class FileForm(forms.ModelForm):
    document = forms.FileField(required=True)
    class Meta:
        model = File
        fields = ('document',)


class GTINForm(forms.Form):
    gtin = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'scan item GTIN or ATTN...','rows':1}), label='')

    

ship_station/templates/aviva_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/ship_station/index/">Aviva</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ship_station:inventorylog-list' %}">All Products</a>
          <!-- <a class="nav-link" href="/admin/ship_station/product/">All Products</a> -->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ship_station:index' %}">Check Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ship_station:increase' %}">Increase +</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ship_station:decrease' %}">Decrease -</a>
        </li>
        
        
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>

ship_station/templates/aviva_pagination.html
<ul class="pagination">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
      </li>
      <li>
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          {{ page_obj.previous_page_number }}
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          {{ page_obj.next_page_number }}
        </a>
      </li>
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
    {% endif %}

  </ul>
</nav>

ship_station/templates/decrease.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Inventory Management | Aviva San Antonio</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<!-- Bootstrap CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>

  <body>

    {% include 'aviva_navbar.html' %}

    <main role="main" class="container">

      <div class="starter-template">
        <audio id='alarm-sound' src="{% static 'img/mixkit-classic-alarm-995.wav' %}"></audio>
        <audio id='success-sound' src="{% static 'img/mixkit-player-losing-or-failing-2042.wav' %}"></audio>
        <p id="item-name"></p>
        <strong><p style='font-size:40px;' id="item-quantity"></p></strong>
        <form id="decrease" action="{% url 'ship_station:decrease' %}" method="POST">{% csrf_token%}
            {{ form.as_p }}
            <input class="btn btn-danger btn-lg" id="submit-button" type="submit" value="DECREASE -">
        </form>
        <script type="text/javascript">
            $(document).ready(function(){
                $("#id_gtin").focus();

              $("#decrease").submit(function(e){
                $('#submit-button').prop('disabled',true)

                function disableInput() {
                  $('#id_gtin').prop('disabled',true)
                };
                setTimeout(disableInput,200)
                // prevent from normal form behaviour
                console.log('submit edildi')
                e.preventDefault();
                // serialize the form data  
                var serializedData = $(this).serialize();
                $.ajax({
                    type : 'POST',
                    url :  "{% url 'ship_station:decrease' %}",
                    data : serializedData,
                    success : function(response){
                      function enableButton(params) {
                        $('#submit-button').prop('disabled',false)
                      }
                      setTimeout(enableButton,2000)

                      function enableInput() {
                        $('#id_gtin').prop('disabled',false)
                        $("#id_gtin").focus();
                      };
                      setTimeout(enableInput,2000)

                      console.log(response);
                      if(response.result == 429){
                        document.getElementById('alarm-sound').play();
                        alert('System stopped for 24 hours'); 
                      }
                      if(response.result == 'invalid_barcode'){
                        document.getElementById('alarm-sound').play();
                        alert('invalid barcode'); 
                      }
                      if(response.result == 'sold'){
                        document.getElementById('success-sound').play();
                        $('#item-name').html(response.itemName);
                        $('#item-quantity').html(response.itemQuantity);
                      };
                      if(response.result == 'not_found'){
                        document.getElementById('success-sound').play();
                        $('#item-name').html(response.itemName);
                        $('#item-quantity').html(response.itemQuantity);
                      }
                      $('#id_gtin').val('');
                      $("#id_gtin").focus();
                    },
                    error : function(response){
                        console.log(response)
                    }
                });
               });
            });
            </script>
        
    </div>

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
</body>
</html>

ship_station/templates/increase.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Inventory Management | Aviva San Antonio</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<!-- Bootstrap CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>

  <body>

    {% include 'aviva_navbar.html' %}

    <main role="main" class="container">

      <div class="starter-template">
        <audio id='alarm-sound' src="{% static 'img/mixkit-classic-alarm-995.wav' %}"></audio>
        <audio id='success-sound' src="{% static 'img/mixkit-ethereal-fairy-win-sound-2019.wav' %}"></audio>
        <p id="item-name"></p>
        <strong><p style='font-size:40px;' id="item-quantity"></p></strong>
        <form id="increase" action="{% url 'ship_station:increase' %}" method="POST">{% csrf_token%}
            {{ form.as_p }}
            <input class="btn btn-primary btn-lg" id="submit-button" type="submit" value="INCREASE +">
        </form>
        <script type="text/javascript">
            $(document).ready(function(){
                $("#id_gtin").focus();
               $("#increase").submit(function(e){
                // prevent from normal form behaviour
                $('#submit-button').prop('disabled',true)

                function disableInput() {
                  $('#id_gtin').prop('disabled',true)
                };
                setTimeout(disableInput,200)

                 console.log('submit edildi')
                      e.preventDefault();
                    // serialize the form data  
            
                      var serializedData = $(this).serialize();
                      $.ajax({
                          type : 'POST',
                          url :  "{% url 'ship_station:increase' %}",
                          data : serializedData,
                          success : function(response){
                            function enableButton(params) {
                              $('#submit-button').prop('disabled',false)
                            }
                            setTimeout(enableButton,2000)

                            function enableInput() {
                              $('#id_gtin').prop('disabled',false)
                              $("#id_gtin").focus();
                            };
                            setTimeout(enableInput,2000)
                            
                            console.log(response)
                            if(response.result == 'invalid_barcode'){
                              document.getElementById('alarm-sound').play();
                              $('#item-name').html(response.itemName);
                              $('#item-quantity').html(response.itemQuantity);
                            }
                            if(response.result == 'restocked'){
                              document.getElementById('success-sound').play();
                              $('#item-name').html(response.itemName);
                              $('#item-quantity').html(response.itemQuantity);
                            }
                            $('#id_gtin').val('');
                            $("#id_gtin").focus();
                          },
                          error : function(response){
                              console.log(response)
                          }
                      });
               });
            });
            </script>
        
    </div>

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
</body>
</html>

ship_station/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Inventory Management | Aviva San Antonio</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	  <!-- Bootstrap CSS -->
	  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>

    {% include 'aviva_navbar.html' %}

    <main role="main" class="container">

      <div class="starter-template">
        <h4>Aviva San Antonio Inventory Management Portal</h4>
        <br>
        <p id="item-name"></p>
        <strong><p style='font-size:40px;' id="item-quantity"></p></strong>
        <form id="check-status-form" method="post">{% csrf_token %}
          {{ form.as_p }}
          <input class="btn btn-secondary btn-lg btn-block" type="submit" value="Check Status">
        </form>
        <script>
          $(document).ready(function(){
            $("#id_gtin").focus();

            $("#check-status-form").submit(function(e){
              e.preventDefault();
              console.log('submit edildi');
              var serializedData = $(this).serialize();
              $.ajax({
                    type : 'POST',
                    url :  "{% url 'ship_station:index' %}",
                    data : serializedData,
                    success : function(data){
                      $('#id_gtin').val(''); 
                      $("#id_gtin").focus();
                      $('#item-name').html(data.itemName);
                      $('#item-quantity').html(data.itemQuantity);
                    },
                    error : function(data){

                    },
              });
            });
          });
        </script>
        
        <br><br><hr><br>
        <form action="{% url 'ship_station:increase' %}" >
            <button type="submit" class="btn btn-primary btn-lg btn-block">Increase +</button>
        </form><br>

        <form action="{% url 'ship_station:decrease' %}">
            <button type="submit" class="btn btn-danger btn-lg btn-block">Decrease -</button>
        </form>
        
        
        
    </div>

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>